name: Cypress work flow

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: "Select the env."
        required: true
        default: prod

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm i

      - name: Run Cypress tests
        run: npx cypress run
