name: workflow2
on: 
  push:
    branches:
      - 'main'
  workflow_dispatch:
  schedule:
    -cron: '*/5 22 * * 6'

jobs:
  checkout-and-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: run cypress tests with firefox
        uses: cypress-io/github-action@v2
        timeout-minutes: 10
        with:
          start: npm run test
          config-file: cypress.json
          record: true
          parallel: true
          browser: chrome
          spec: |
            cypress/integration/*.feature

