name: workflow
on: 
  push:
    branches:
      -main
    schedule:
      -cron: '*/5 22 * * 6'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Running
      run: |
        echo "Running!"
