name: workflow
on: 
  schedule:
    - cron: '* * * * *'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Cypress run
        run: echo "Hello g"
#         with:
#           start: npm run test
#           config-file: cypress.json
#           browser: chrome
#           spec: |
#             cypress/integration/*.feature
