name: workflow
on: 
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:
    inputs:
      environment:
        description: "In which environment you want to run (test,beta)"
        required: true
        default: "test"

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Cypress run
        with:
          start: npm run test
          config-file: cypress.json
          record: true
          parallel: true
          browser: chrome
          spec: |
            cypress/integration/*.feature
